apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed
  selector:
    matchLabels:
         name: sqlserver  
  resources:
    requests:
      storage: 5Gi
